spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v1/product/**, /v1/category/**, /v1/productimage/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/v1/order/**
      discovery:
        locator:
          enabled: true
server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
